### ISSUE TITLE
Border - Defaults to `medium`

### ISSUE THREAD

**Issue by bryanbill** [bryanbill/kitawi#17]
# Expected behaviour
Border with with undefined sides (left, top, bottom, right) i.e null, or Border() without any param provided should be treated as a 'non-existent property'

# Actual Behaviour
Providing `border: Border()` in a [Container](https://pub.dev/documentation/kitawi/latest/kitawi/Container-class.html) set's the default border-width to `medium`

See [MDN Web Docs - border-width](https://developer.mozilla.org/en-US/docs/Web/CSS/border-width) for Design Specifications

**Comment by TrekHub** [comment]
https://meet.google.com/wer-rtjs-nzh
